on:
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write


jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #          - os: ubuntu-latest
          #            artifact_name: db-gen
          #            asset_name: db-gen-linux-amd64
          - os: windows-latest
            binary_name: win-db-gen.exe

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build -x -v -o ${{ matrix.binary_name }} .
      - name: LS
        run: ls
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ matrix.binary_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}