on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write


jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
#          - os: ubuntu-latest
          #            artifact_name: db-gen
          #            asset_name: db-gen-linux-amd64
          - os: windows-latest
            artifact_name: db-gen.exe
            asset_name: db-gen-windows-amd64

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build -x -v ./...
      - name: LS
        run: ls -la
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}