name: Create release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish for ${{ matrix.goos }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            binary: db-gen-linux
          - goarch: amd64
            goos: windows
            binary: db-gen-win.exe

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: add version
        run: echo "GITHUB_ACTIONS ${{  github.ref_name }} unknown" > version.txt
      - name: check version
        run: cat version.txt
      - name: Build
        run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o ${{ matrix.binary }} .
      - name: LS
        run: ls
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.binary }}
            
