on:
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write


jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            binary: db-gen-win
          - goarch: amd64
            goos: windows
            binary: db-gen-win.exe

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o ${{ matrix.binary }} .
      - name: LS
        run: ls
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ matrix.binary }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}